# Top Level Params
log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp8_mse_aliveunet_v1.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp8_mse_aliveunet_v1'
result_path: 'results6_e2e_p2.txt'

GENERAL:
  save_freq: 16
  seed: 1

DATA:
  folder: '/kuacc/users/bsefercik/dataset/alivev1'
  suffix: .pickle
  prefix: ''
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  file_names: null

  workers: 4
  batch_size: 24  # v100->26, t4->8 mink18d

  scale: 100  # voxel_size (=quantization_size) = 1 / scale, scale 50 (2cm)
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4  # 4: mean
  input_channel: 3 # rgb or gray

  classes: 2
  ignore_label: -100
  pose_dim: 7

  test_split: 'test'

STRUCTURE:
  m: 32 # 16 or 32
  block_reps: 2
  block_residual: True
  use_coords: True

TRAIN:
  fixed_modules: []
  optim: 'Adam' # Adam or SGD

  epochs: 1300
  lr: 0.0001
  momentum: 0.9
  weight_decay: 0.0001
  multiplier: 0.5
  step_epoch: 30

  data_type: "none"  #'seg'  # ['seg', 'gt_seg', null]
  loss_type: "mse"
  loss_reduction: "sum"

TEST:
  batch_size: 2
  split: test
  workers: 2
  seed: 13
  epoch: 320

