# Top Level Params
log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/ycb_fe_exp3_05.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/ycb_fe_exp3_05'
result_path: 'results6_e2e_p2.txt'

GENERAL:
  save_freq: 16
  seed: 13

DATA:
  folder: '/datasets/ycb_objects'
  suffix: .pcd
  prefix: ''
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/ycb_splits.json'

  workers: 4  # 4
  batch_size: 256
  max_pair: 512

  scale: 200  # voxel_size (=quantization_size) = 1 / scale, scale 50 (2cm)
  full_scale: [128, 512]
  max_npoint: 250000
  min_npoints: 0 # 8
  mode: 4  # 4: mean
  input_channel: 3 # rgb or gray

  classes: 2
  ignore_label: -100
  pose_dim: 7

  test_split: 'test'

STRUCTURE:
  m: 32 # 16 or 32  TODO: what is it?
  block_reps: 2
  block_residual: True
  use_coords: True
  embedding_size: 512

TRAIN:
  fixed_modules: []
  optim: 'Adam' # Adam or SGD

  epochs: 1300
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001
  multiplier: 0.5
  step_epoch: 40

  data_type: "none"  #'seg'  # ['seg', 'gt_seg', null]

TEST:
  batch_size: 20
  split: test
  workers: 2
  seed: 13
  checkpoint: default_fe-000000832.pth
  print_precision: 4


