# Top Level Params
log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/default.log
exp_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/default

MODE: 'train'

PARAM:
  ee_r: 0.02  # m

GENERAL:
  save_freq: 4
  seed: 1

DATA:
  folder: '/kuacc/users/bsefercik/dataset/alivev5'
  suffix: .pickle
  prefix: ''
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_splits_all_train.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  load_cache_at_start: true

  workers: 0
  batch_size: 2 # v100->26, t4->8 mink18d

  scale: 100  # voxel_size (=quantization_size) = 1 / scale, scale 50 (2cm)
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4  # 4: mean
  input_channel: 3 # rgb or gray

  classes: 3  # 0: bg, 1: robot arm, 2: end-effector
  ignore_label: -100
  pose_dim: 7

  test_split: 'test'
  data_type: ee_seg  #'seg'  # ['seg', 'gt_seg', null, gt_bbox, ee_seg]

  position_eligibility_enabled: false
  orientation_eligibility_enabled: false

  voting_enabled: false

  voxelize_position: false

  center_at_origin: true
  base_at_origin: false

  move_ee_to_origin: false

  ee_segmentation_enabled: true

  quantization_enabled: true

  keypoints_enabled: false

  use_coordinates_as_features: false
  num_of_keypoints: 6  # or 10
  num_of_dense_input_points: 2048
  use_point_normals: false
  pointcloud_sampling_method: farthest  # uniform

  augmentation: []  # select from: [elastic, noise, transform, flip, gravity]
  augmentation_probability: 0.2

  roi: null  # example: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']
  roi_offset: 0.13  # in meters


STRUCTURE:
  m: 32 # 16 or 32
  block_reps: 2
  block_residual: true
  use_coords: true

  use_joint_angles: false

  bottleneck: true
  backbone: 'minkunet'
  encode_only: false

  compute_confidence: false
  position_threshold : 0.03  # m
  position_ignore_threshold : 0.05  # m
  angle_diff_threshold: 0.24  # rad
  angle_diff_ignore_threshold: 0.4  # rad

  disable_position: false
  disable_orientation: false

TRAIN:
  fixed_modules: []
  optim: 'Adam' # Adam or SGD

  epochs: 1300
  lr: 0.0001
  momentum: 0.8
  weight_decay: 0.0001
  multiplier: 0.8
  step_epoch: 16

  loss_type: "cos2"
  loss_reduction: "mean"

  kp_prediction_checkpoint: null  # only for kp_to_pose
  kp_use_probabilities: true

TEST:
  seed: 1

  batch_size: 2
  split: test
  workers: 2
  seed: 13
  epoch: 124
  checkpoint: default_cos2_v2_18d-000000456.pth
  print_precision: 4

  rotation_results: null
  translation_results: null

  data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json

  output: test_results.xlsx

  ignore_unconfident: true

  gt_base_to_cam_pose: [0.645, 0.408, 0.994, 0.656, 0.2964, 0.2756, -0.6299]  # p1 tf_broadcaster (x, y, z, qw, qx, qy, qz)

  SEGMENTATION:
    evaluate: true

  KEY_POINTS:
    error_margin: 0.05  # in meters

  units: ['m', 'rad']

INFERENCE:
  data_source: /kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json

  ee_point_counts_threshold: 512

  icp_enabled: true

  # /camera_rgb_optical_frame to /camera_link
  # camera_link_transformation_pose: [0.000, 0.000, -0.045, 0.500, 0.500, -0.500, 0.500]  # official
  # camera_link_transformation_pose: [0.0062, 0.0309, -0.0454, 0.4688, 0.4857, -0.507, 0.536]
  camera_link_transformation_pose: null

  SANITY:
    min_num_of_ee_points: 3000

  INPUT:
    roi: {}

  SEGMENTATION:
    checkpoint: /kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp36_seg_origin_s200/default-000000008.pth
    backbone: 'robotnet_segmentation'
    classes: ['background', 'arm', 'ee']
    class_colors: ['2C3E50', 'E74C3C', 'F1C40F']
    scale: 200
    center_at_origin: true

  TRANSLATION:
    checkpoint: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp34_vote_origin/default-000000096.pth'
    backbone: 'minkunet'
    scale: 200
    center_at_origin: true
    move_ee_to_origin: true
    magic_enabled: false

  ROTATION:
    backbone: 'minkunet'
    encode_only: true
    scale: 200
    checkpoint: /kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp38_ee_seg_geodesic_origin/default-000000072.pth
    center_at_origin: true

  KEY_POINTS:
    checkpoint: /kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp45_kp6_pt2_coord_center_uniform_aug/default-000000114.pth
    backbone: 'pointnet2'
    scale: 800
    center_at_origin: true
    conf_threshold: 0.75
    use_coordinates_as_features: false
    num_of_keypoints: 6
    error_margin: 0.05  # in meters
    pointcloud_sampling_method: uniform  # choices: farthest, uniform

  CALIBRATION:
    num_of_frames: 10
    min_num_of_positions: 5
    pcd_source: /home/ercan/bcs_workspace/bcs_ssd/bags/20220627_training/p3_fair_full/pcd_ee
