# Top Level Params
log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp8_cos2_aliveunet_v2_gt-seg_18d.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp8_cos2_aliveunet_v2_gt-seg_18d'
result_path: 'results6_e2e_p2.txt'

GENERAL:
  save_freq: 4
  seed: 1

DATA:
  folder: '/kuacc/users/bsefercik/dataset/alivev2'
  suffix: .pickle
  prefix: ''
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: null

  workers: 4
  batch_size: 5 # v100->26, t4->8 mink18d

  scale: 100  # voxel_size (=quantization_size) = 1 / scale, scale 50 (2cm)
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4  # 4: mean
  input_channel: 3 # rgb or gray

  classes: 2
  ignore_label: -100
  pose_dim: 7

  test_split: 'test'
  data_type: "gt_seg"  #'seg'  # ['seg', 'gt_seg', null, gt_bbox]

STRUCTURE:
  m: 32 # 16 or 32
  block_reps: 2
  block_residual: True
  use_coords: True

  bottleneck: True
  backbone: 'minkunet'

TRAIN:
  fixed_modules: []
  optim: 'Adam' # Adam or SGD

  epochs: 1300
  lr: 0.0001
  momentum: 0.8
  weight_decay: 0.0001
  multiplier: 0.8
  step_epoch: 16

  loss_type: "cos2"
  loss_reduction: "sum"

TEST:
  batch_size: 2
  split: test
  workers: 2
  seed: 13
  epoch: 124
  checkpoint: "default_cos2_v2_18d-000000124.pth"
  print_precision: 4

