log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp10_alivev3_gt-seg_10000.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev3_gt-seg_10000'

GENERAL:
  save_freq: 24

DATA:
  batch_size: 32
  data_type: gt_seg
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  arm_point_count_threshold: 10000
