MODE: 'inference'

DATA:
  batch_size: 2

  folder: '/home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2'
  file_names: '/home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json'

INFERENCE:
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v5_splits.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/p1_calib_2.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v5_splits.json
  data_source: null
  ee_point_counts_threshold: 512
  num_of_dense_input_points: 2048
  camera_link_transformation_pose: [0.0062, 0.0309, -0.0454, 0.4688, 0.4857, -0.507, 0.536]

  icp_enabled: true

  INPUT:
    roi: {}

  SEGMENTATION:
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/segmentation_s200_origin_robotnet_20220509.pth
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/seg_exp50_orig_aug_s200_e6.pth
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/seg_exp53_orig_aug_s200_15_e8.pth
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/seg_exp53_orig_aug_s200_08_e17.pth
    scale: 200
    center_at_origin: true

  TRANSLATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/translation_s200_origin_move-ee_20220509.pth
    scale: 200
    center_at_origin: true
    move_ee_to_origin: true
    magic_enabled: true

  ROTATION:
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/rotation_s200_posematch_origin_e104_20220509.pth
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/exp51_ee_seg_rot_origin_e96_s200.pth
    center_at_origin: true

  KEY_POINTS:
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/key_points_origin_coords-only_e48_kp6_s200_20220515.pth  # minkunet
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/kp6_pt2_coord_center_farthest_e52_20220519.pth # best so far
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/exp45_kp6_pt2_coord_center_farthest_aug_e148_20220520.pth
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/exp45_kp6_pt2_coord_center_uniform_aug_e114_20220520.pth

    scale: 200
    center_at_origin: true
    use_coordinates_as_features: true
    conf_threshold: 0.75
    backbone: pointnet2
    num_of_keypoints: 6
    pointcloud_sampling_method: uniform  # choices: farthest, uniform

exp_path: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference
log_path: /home/ercan/bcs_workspace/unknown_object_segmentation/log/inference.log