log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp51_ee_seg_rot_origin_p3.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp51_ee_seg_rot_origin_p3'

GENERAL:
  save_freq: 8

DATA:
  batch_size: 32
  workers: 4
  # batch_size: 2
  # workers: 0
  data_type: 'ee_seg'


  num_of_dense_input_points: 4096
  load_cache_at_start: true
  pointcloud_sampling_method: uniform  # farthest, uniform, null

  use_coordinates_as_features: true
  use_point_normals: true

  scale: 200

  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_splits_all_train.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev5_p3_splits.json'
  # arm_point_count_threshold: 20000

  # roi:  [ '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # roi:  ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']
  # roi_offset: 0.13  # m

  position_eligibility_enabled: false
  orientation_eligibility_enabled: false

  center_at_origin: true
  base_at_origin: false

  move_ee_to_origin: false

STRUCTURE:
  backbone: 'minkunet'
  # backbone: 'pointnet2'
  encode_only: true

  compute_confidence: false
  disable_position: true
  disable_orientation: false

TRAIN:
  loss_type: "pose"
  loss_reduction: mean

TEST:
  batch_size: 2
  split: test
  workers: 1
  checkpoint: default_cos2_v2_18d-000000384.pth
