log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp9_cos2_v2_alive_34c.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp9_cos2_v2_alive_34c'

GENERAL:
  save_freq: 12

DATA:
  batch_size: 16

STRUCTURE:
  backbone: 'minkunet34C'
