log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp10_alivev2+3_gt-seg_20000.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev2+3_gt-seg_20000'

GENERAL:
  save_freq: 24

DATA:
  batch_size: 2
  data_type: gt_seg
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits_hdd.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000
  workers: 0

STRUCTURE:
  backbone: 'minkunet'

TEST:
  batch_size: 3
  split: test
  workers: 3
  checkpoint: default_cos2_v2_18d-000000192.pth