log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp8_cos2_aliveunet_v1_gt-bbox_18d.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp8_cos2_aliveunet_v1_gt-bbox_18d'

GENERAL:
  save_freq: 16

DATA:
  batch_size: 12
  data_type: gt_bbox
