MODE: 'inference'

TEST:
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v4_splits.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v4_splits_dummy.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/pred_test_splits.json
  data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v5_splits.json
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/p1_calib_2.json

  output: test_results_p1_calib_v7_gtseg__.xlsx

  ignore_unconfident: true

  # gt_base_to_cam_pose: [0.645, 0.408, 0.994, 0.656, 0.2964, 0.2756, -0.6299]  # p1 tf_broadcaster (x, y, z, qw, qx, qy, qz)
  # gt_base_to_cam_pose: [0.65, 0.3546, 0.9807, -0.0236, -0.0027, 0.9332, -0.3586]
  gt_base_to_cam_pose: [0.6265, 0.3674, 0.9880, -0.0092, -0.0007, 0.9296, -0.3684]

  units: ['cm', 'degree']
  # units: ['m', 'rad']

  SEGMENTATION:
    evaluate: false

  KEY_POINTS:
    error_margin: 0.04  # in meters

INFERENCE:
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json
  data_source: null
  ee_point_counts_threshold: 512
  num_of_dense_input_points: 2048

  # /camera_rgb_optical_frame to /camera_link
  # camera_link_transformation_pose: [0.00, -0.045, 0.00, 0.500, 0.500, -0.500, 0.500]  # official
  # camera_link_transformation_pose: [0.0062, 0.0309, -0.0454, 0.4688, 0.4857, -0.507, 0.536]
  camera_link_transformation_pose: null

  kinect1_weight_polynomials: [-1.08e-03, -5.73e-05, 1.85E-03]  # [a, b, c] = c + bx + ax^2

  SANITY:  # TODO: add this to default.yaml
    min_num_of_ee_points: 4096

  INPUT:
    roi: {}

  SEGMENTATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/segmentation_s200_origin_robotnet_20220509.pth
    scale: 200
    center_at_origin: true

  TRANSLATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/translation_s200_origin_move-ee_20220509.pth
    scale: 200
    center_at_origin: true
    move_ee_to_origin: true
    magic_enabled: true

  ROTATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/rotation_s200_posematch_origin_e104_20220509.pth
    center_at_origin: true

  KEY_POINTS:
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/key_points_origin_coords-only_e48_kp6_s200_20220515.pth  # minkunet
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/kp6_pt2_coord_center_farthest_e52_20220519.pth # best so far
    # checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/exp45_kp6_pt2_coord_center_farthest_aug_e148_20220520.pth
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/exp45_kp6_pt2_coord_center_uniform_aug_e114_20220520.pth

    scale: 200
    center_at_origin: true
    use_coordinates_as_features: true
    conf_threshold: 0.75
    backbone: pointnet2
    num_of_keypoints: 6
    pointcloud_sampling_method: uniform  # choices: farthest, uniform

exp_path: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference
log_path: /home/ercan/bcs_workspace/unknown_object_segmentation/log/inference.log