# log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp16_alivev2+3_3layers_avgpool.log
# exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp16_alivev2+3_3layers_avgpool'

log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp22_geodesic_eemask_s200.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp22_geodesic_eemask_s200'

GENERAL:
  save_freq: 24

DATA:
  batch_size: 52
  # batch_size: 2
  workers: 4
  data_type: 'ee_seg'

  scale: 200

  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_splits_all_train.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000

  # roi:  [ '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # # roi:  ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  # #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # # roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']
  # roi_offset: 0.13  # m

  position_eligibility_enabled: true
  orientation_eligibility_enabled: true

STRUCTURE:
  backbone: 'minkunet'
  encode_only: true

  compute_confidence: true
  disable_position: false
  disable_orientation: false

  compute_confidence: false

TRAIN:
  loss_type: "wgeodesic"
  loss_reduction: "sum"

TEST:
  batch_size: 2
  split: test
  workers: 1
  checkpoint: default_cos2_v2_18d-000000384.pth
