log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp14_alivev2+3_full.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp14_alivev2+3_full'

# exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev2+3_20000'
# log_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp10_alivev2+3_20000.log'

GENERAL:
  save_freq: 16

DATA:
  batch_size: 6
  data_type: null
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000


STRUCTURE:
  backbone: 'minkunet'
  encode_only: false

  # compute_confidence: false

TEST:
  batch_size: 6
  split: test
  workers: 1
  checkpoint: default_cos2_v2_18d-000000112.pth
