DATA:
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']

  position_eligibility_enabled: false
  orientation_eligibility_enabled: false

TEST:
  batch_size: 8
  split: test
  workers: 3
  checkpoint: default-000000304.pth
