log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp10_alivev3_20000_t4.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev3_20000_t4'

GENERAL:
  save_freq: 4

DATA:
  batch_size: 3
  data_type: null
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  arm_point_count_threshold: 20000
