log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp12_alivev2+3_gt-seg.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp12_alivev2+3_gt-seg'

GENERAL:
  save_freq: 24

DATA:
  batch_size: 96
  data_type: gt_seg
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits_hdd.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000
  workers: 3

STRUCTURE:
  backbone: 'minkunet'
  encode_only: true

TEST:
  batch_size: 24
  split: test
  workers: 3
  checkpoint: default_cos2_v2_18d-000000312.pth