log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp37_vote_origin_move-ee_s200.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp37_vote_origin_move-ee_s200'

GENERAL:
  save_freq: 16

DATA:
  batch_size: 12
  # batch_size: 2
  workers: 4
  data_type: 'ee_seg'

  scale: 200

  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_splits_all_train.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev4_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000

  roi:  [ '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_limits.json',
          '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
          '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # roi:  ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev4_limits.json']
  # roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']
  roi_offset: 0.13  # m

  position_eligibility_enabled: true
  orientation_eligibility_enabled: true

  voting_enabled: true

  center_at_origin: true
  base_at_origin: false

  move_ee_to_origin: true  # only use it when data_type: ee_seg

TRAIN:
  loss_reduction: "sum"

STRUCTURE:
  backbone: 'minkunet'
  loss_type: "wgeodesic"

  # compute_confidence: false

VOTE:
  count: 32
  pred_count: 4  # TODO: implement it for train, test, pred
  cutoff: 0.005

TEST:
  batch_size: 2
  split: test
  workers: 1
  checkpoint: default-000000008.pth