log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/dev.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/dev'

DATA:
  batch_size: 2
  workers: 0

  center_at_origin: true
