log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/test.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev2+3_20000'

GENERAL:
  save_freq: 4

DATA:
  batch_size: 3
  data_type: null
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  arm_point_count_threshold: 10000

STRUCTURE:
  backbone: 'minkunet'

TEST:
  batch_size: 3
  split: test
  workers: 3
  checkpoint: default_cos2_v2_18d-000000052.pth
