MODE: 'inference'

DATA:
  batch_size: 2

  folder: '/home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2'
  file_names: '/home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json'

INFERENCE:
  # data_source: /home/ercan/bcs_workspace/unknown_object_segmentation/dataset/alive_test_v2_splits.json
  data_source: null

  INPUT:
    roi: {}

  SEGMENTATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/segmentation_s200_origin_robotnet_20220509.pth
    scale: 200
    center_at_origin: true

  TRANSLATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/translation_s200_origin_move-ee_20220509.pth
    scale: 200
    center_at_origin: true
    move_ee_to_origin: true
    magic_enabled: true

  ROTATION:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/rotation_s200_posematch_origin_e104_20220509.pth
    center_at_origin: true

  KEY_POINTS:
    checkpoint: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference/key_points_origin_coords-only_e48_kp6_s200_20220515.pth
    scale: 200
    center_at_origin: true
    use_coordinates_as_features: true
    conf_threshold: 0.99

exp_path: /home/ercan/bcs_workspace/unknown_object_segmentation/exp/inference
log_path: /home/ercan/bcs_workspace/unknown_object_segmentation/log/inference.log