# Top Level Params
log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp36_seg_origin_allarmee_s200.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp36_seg_origin_allarmee_s200'

GENERAL:
  save_freq: 2
  seed: 1

DATA:
  suffix: .pickle
  prefix: ''
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev1_splits_all_train.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'

  workers: 4
  batch_size: 3

  scale: 200 # voxel_size (=quantization_size) = 1 / scale, scale 50 (2cm)
  full_scale: [128, 512]
  max_npoint: 250000
  mode: 4  # 4: mean
  input_channel: 3 # rgb or gray

  classes: 3  # 0: bg, 1: robot arm, 2: end-effector
  ignore_label: -100
  pose_dim: 7

  test_split: 'test'
  data_type: null  #'seg'  # ['seg', 'gt_seg', null]

  ee_segmentation_enabled: true

  center_at_origin: true

  position_eligibility_enabled: true
  orientation_eligibility_enabled: true

  # roi:  ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_limits.json',
  #         '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_limits.json']
  # # roi: ['/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_limits.json']
  # roi_offset: 0.13  # m

STRUCTURE:
  m: 32 # 16 or 32
  block_reps: 2
  block_residual: True
  use_coords: True

  use_joint_angles: False

  bottleneck: True
  backbone: 'minkunet'
TRAIN:
  fixed_modules: []
  optim: 'Adam' # Adam or SGD

  epochs: 1300
  lr: 0.0001
  momentum: 0.8
  weight_decay: 0.0001
  multiplier: 0.8
  step_epoch: 16

  loss_reduction: "sum"

TEST:
  batch_size: 2
  split: test
  workers: 1
  seed: 13
  epoch: 232
  checkpoint: "default_cos2_v1_18d-000000232.pth"
  print_precision: 4

