log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp10_alivev3_gt-seg_30000.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp10_alivev3_gt-seg_30000'

GENERAL:
  save_freq: 24

DATA:
  batch_size: 32
  data_type: gt_seg
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  arm_point_count_threshold: 30000

STRUCTURE:
  backbone: 'minkunet'

TEST:
  batch_size: 3
  split: test
  workers: 3
  checkpoint: default_cos2_v2_18d-000000052.pth
