log_path: /kuacc/users/bsefercik/repos/unknown_object_segmentation/log/exp13_segmentation_18d.log
exp_path: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/exp/exp13_segmentation_18d'

GENERAL:
  save_freq: 16

DATA:
  batch_size: 12
  data_type: null
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev2_splits.json,/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  # file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alivev3_splits.json'
  file_names: '/kuacc/users/bsefercik/repos/unknown_object_segmentation/others/alive_test_v2_splits.json'

  # arm_point_count_threshold: 20000

TEST:
  batch_size: 2
  split: test
  workers: 3
  checkpoint: segmentation_18d-000000008.pth
